[tools]
bat = "0.25.0"
bat-extras = "2024.08.24"
fzf = "0.60.3"
gopass = "1.15.15"
lua-language-server = "3.13.6"
neovim = "0.11.1"
node = "23.9.0"
python = "3"
ruby = "3.4.4"
usage = "latest"
yarn = "1.22.22"
lua = "5.4.7"
make = "4.4.1"
markdownlint-cli2 = "0.17.2"
uv = "latest"
pipx = "1.7.1"
perl = "5.40.1"
packer = "1.12.0"
poetry = "2.1.1"
semtag = "0.1.1"
terraform-validator = "3.1.3"
terraform = "1.11.1"
terraform-ls = "0.36.4"
rust = "1.85.0"
ripgrep = "14.1.1"
pre-commit = "4.1.0"
zoxide = "latest"
fd = "latest"
terraform-lsp = "latest"
semver = "latest"
yq = "latest"
tree-sitter = "latest"
tmux = "latest"

[settings]
env_file = '.env'
plugin_autoupdate_last_check_duration = '1 week'
