[tools]
bat = "latest"
bat-extras = "latest"
fzf = "latest"
gopass = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "latest"
python = "latest"
ruby = "latest"
usage = "latest"
yarn = "latest"
lua = "latest"
make = "latest"
markdownlint-cli2 = "latest"
uv = "latest"
pipx = "latest"
perl = "latest"
packer = "latest"
poetry = "latest"
semtag = "latest"
terraform-validator = "latest"
terraform = "latest"
terraform-ls = "latest"
rust = "latest"
ripgrep = "latest"
pre-commit = "latest"
zoxide = "latest"
fd = "latest"
terraform-lsp = "latest"
semver = "latest"
yq = "latest"
tree-sitter = "latest"
tmux = "latest"
"pipx:ansible-core" = "2.16.6"
black = "latest"
"pipx:autopep8" = "latest"
jq = "latest"
"pipx:pydocstyle" = "latest"
shfmt = "latest"
tflint = "latest"
"pipx:yapf" = "latest"
"pipx:ansible-lint" = "latest"
editorconfig-checker = "latest"
glow = "latest"
"pipx:mdformat" = "latest"
"pipx:pyflakes" = "latest"
"pipx:rstcheck" = "latest"
"pipx:sphinx-lint" = "latest"
yamlfmt = "latest"
"pipx:flake8" = "latest"
"pipx:ansible" = "9.5.1"
yamllint = "latest"
shellcheck = "latest"
"pipx:pylint" = "latest"
"ubi:alesbrelih/gitlab-ci-ls" = "latest"
"pipx:python-lsp-server" = "latest"
"ubi:uros-5/jinja-lsp" = "latest"
gh = "latest"
"pipx:gitlab-search" = "latest"

[settings]
env_file = '.env'
plugin_autoupdate_last_check_duration = '1 week'
